### ISSUE TITLE
some file.h are missing????

### ISSUE THREAD

**Issue by ncoah** [arturoc/ofxEchoCancel#1]
Hi arturoc,
I'm resolving the echo problem when streaming audio full-duplex and I want to use your project as a reference.
But I can't find three file.h below so I can't build successful. Can you tell me where i can find them?
# include "ofParameter.h"
# include "ofConstants.h"
# include "ofParameterGroup.h"

Thanks you!

**Comment by arturoc** [comment]
This repository is an addon for [openFrameworks](http://openframeworks.cc) so it will only work when used with it

**Comment by ncoah** [comment]
Thanks you for your answer, arturoc !!
btw, i'm facing a problem that i need support.
I'm working on an Linux embedded development kit using DM3730 processor of TI.
The sound is so much echo when streaming audio full-duplex between two devices.
Can you give me the solutions to cancel the echo when streaming? 
Can i use openFrameworks?
Thanks for your support !!
p/s: my English is not good. :D

**Comment by arturoc** [comment]
most of the code here, the part that does the actual echo cancellation is taken from the echo cancellation code in the webrtc project that both mozilla and chrome use. this algorithm in particular is also used in pulse audio and it works pretty well there. if you are using linux perhaps an easier solution is to use the echo cancelling module in pulse audio since that will do all the latency calculations... for you and it's much easier to integrate than directly this code

**Comment by ncoah** [comment]
Thanks you so much for your answer arturoc !!!!
